<?php

declare(strict_types=1);

function env_value(string $key, ?string $default = null): ?string
{
    $value = getenv($key);
    return $value === false ? $default : $value;
}

function env_flag(string $key, bool $default = false): bool
{
    $fallback = $default ? '1' : '0';
    $value = strtolower((string) env_value($key, $fallback));

    return in_array($value, ['1', 'true', 'yes', 'on'], true);
}

function env_int(string $key, int $default = 0): int
{
    return (int) env_value($key, (string) $default);
}

function project_path(string $path): string
{
    if ($path === '') {
        return ROOT_PATH;
    }

    $normalized = str_replace('\\', '/', $path);

    if (preg_match('/^(?:[A-Za-z]:\/|\/|\/\/)/', $normalized) === 1) {
        return rtrim($normalized, '/');
    }

    return rtrim(ROOT_PATH . '/' . ltrim($normalized, '/'), '/');
}

function load_env_file(string $path): void
{
    if (!is_file($path)) {
        return;
    }

    $lines = file($path, FILE_IGNORE_NEW_LINES);

    if ($lines === false) {
        return;
    }

    foreach ($lines as $line) {
        $trimmed = trim($line);

        if ($trimmed === '' || str_starts_with($trimmed, '#')) {
            continue;
        }

        $separatorPosition = strpos($line, '=');

        if ($separatorPosition === false) {
            continue;
        }

        $key = trim(substr($line, 0, $separatorPosition));
        $rawValue = trim(substr($line, $separatorPosition + 1));

        if ($key === '') {
            continue;
        }

        $value = parse_env_value($rawValue);
        putenv($key . '=' . $value);
        $_ENV[$key] = $value;
        $_SERVER[$key] = $value;
    }
}

function parse_env_value(string $rawValue): string
{
    if ($rawValue === '') {
        return '';
    }

    if (
        (str_starts_with($rawValue, '"') && str_ends_with($rawValue, '"'))
        || (str_starts_with($rawValue, "'") && str_ends_with($rawValue, "'"))
    ) {
        $quote = $rawValue[0];
        $value = substr($rawValue, 1, -1);

        if ($quote === '"') {
            $value = str_replace(['\\"', '\\\\', '\\n', '\\r'], ['"', '\\', "\n", "\r"], $value);
        }

        return $value;
    }

    $hashPosition = strpos($rawValue, ' #');

    if ($hashPosition !== false) {
        $rawValue = substr($rawValue, 0, $hashPosition);
    }

    return trim($rawValue);
}

/**
 * @param array<string, string> $values
 */
function write_env_file_values(string $path, array $values): void
{
    $existingLines = is_file($path) ? file($path, FILE_IGNORE_NEW_LINES) : [];

    if ($existingLines === false || $existingLines === []) {
        $examplePath = dirname($path) . '/.env.example';
        $existingLines = is_file($examplePath) ? file($examplePath, FILE_IGNORE_NEW_LINES) : [];
    }

    if ($existingLines === false || $existingLines === []) {
        $existingLines = [
            '# Generated by the admin panel',
        ];
    }

    $pending = $values;
    $result = [];

    foreach ($existingLines as $line) {
        $separatorPosition = strpos($line, '=');
        $trimmed = trim($line);

        if ($separatorPosition === false || $trimmed === '' || str_starts_with($trimmed, '#')) {
            $result[] = $line;
            continue;
        }

        $key = trim(substr($line, 0, $separatorPosition));

        if (array_key_exists($key, $pending)) {
            $result[] = $key . '=' . env_encode_value((string) $pending[$key]);
            unset($pending[$key]);
            continue;
        }

        $result[] = $line;
    }

    if ($pending !== []) {
        if ($result !== [] && trim((string) end($result)) !== '') {
            $result[] = '';
        }

        foreach ($pending as $key => $value) {
            $result[] = $key . '=' . env_encode_value((string) $value);
        }
    }

    $content = implode(PHP_EOL, $result) . PHP_EOL;

    if (file_put_contents($path, $content, LOCK_EX) === false) {
        throw new RuntimeException('Could not save the .env file. Check write permission in the project folder.');
    }
}

function env_encode_value(string $value): string
{
    $escaped = str_replace(
        ['\\', '"', "\n", "\r"],
        ['\\\\', '\\"', '\\n', '\\r'],
        $value
    );

    return '"' . $escaped . '"';
}
