<?php

return [
    [
        'slug' => 'editorial-after-hours',
        'title' => 'Editorial After Hours',
        'synopsis' => 'Clean studio shoot with a premium access tag.',
        'creator_name' => 'Nadia Vale',
        'category' => 'Studio',
        'access_level' => 'premium',
        'duration_minutes' => 42,
        'poster_tone' => 0,
        'poster_path' => null,
        'video_url' => null,
        'file_path' => null,
        'trailer_url' => null,
        'embed_url' => null,
        'mime_type' => null,
        'original_source_url' => null,
        'source_type' => 'upload',
        'storage_provider' => 'local',
        'is_featured' => 1,
        'moderation_status' => 'approved',
        'published_at' => '2026-03-21 19:20:00',
    ],
    [
        'slug' => 'private-loft-series',
        'title' => 'Private Loft Series',
        'synopsis' => 'Solo release with direct presentation and Premium access.',
        'creator_name' => 'Lia North',
        'category' => 'Solo',
        'access_level' => 'premium',
        'duration_minutes' => 28,
        'poster_tone' => 1,
        'poster_path' => null,
        'video_url' => null,
        'file_path' => null,
        'trailer_url' => null,
        'embed_url' => null,
        'mime_type' => null,
        'original_source_url' => null,
        'source_type' => 'upload',
        'storage_provider' => 'local',
        'is_featured' => 1,
        'moderation_status' => 'approved',
        'published_at' => '2026-03-19 22:10:00',
    ],
    [
        'slug' => 'couples-archive-madrid',
        'title' => 'Couples Archive / Madrid',
        'synopsis' => 'Couples set published for Premium subscribers.',
        'creator_name' => 'Atelier 24',
        'category' => 'Couples',
        'access_level' => 'premium',
        'duration_minutes' => 55,
        'poster_tone' => 2,
        'poster_path' => null,
        'video_url' => null,
        'file_path' => null,
        'trailer_url' => null,
        'embed_url' => null,
        'mime_type' => null,
        'original_source_url' => null,
        'source_type' => 'upload',
        'storage_provider' => 'local',
        'is_featured' => 1,
        'moderation_status' => 'approved',
        'published_at' => '2026-03-16 18:40:00',
    ],
    [
        'slug' => 'creator-verified-session-08',
        'title' => 'Creator Verified Session 08',
        'synopsis' => 'Free preview with a verified creator profile.',
        'creator_name' => 'Mika Shore',
        'category' => 'Verified',
        'access_level' => 'free',
        'duration_minutes' => 14,
        'poster_tone' => 3,
        'poster_path' => null,
        'video_url' => null,
        'file_path' => null,
        'trailer_url' => null,
        'embed_url' => null,
        'mime_type' => null,
        'original_source_url' => null,
        'source_type' => 'upload',
        'storage_provider' => 'local',
        'is_featured' => 0,
        'moderation_status' => 'approved',
        'published_at' => '2026-03-15 10:20:00',
    ],
    [
        'slug' => 'studio-ledger-vol-2',
        'title' => 'Studio Ledger Vol. 2',
        'synopsis' => 'Longer studio release for premium users.',
        'creator_name' => 'Studio Ledger',
        'category' => 'Studio',
        'access_level' => 'premium',
        'duration_minutes' => 63,
        'poster_tone' => 1,
        'poster_path' => null,
        'video_url' => null,
        'file_path' => null,
        'trailer_url' => null,
        'embed_url' => null,
        'mime_type' => null,
        'original_source_url' => null,
        'source_type' => 'upload',
        'storage_provider' => 'local',
        'is_featured' => 0,
        'moderation_status' => 'approved',
        'published_at' => '2026-03-12 21:45:00',
    ],
    [
        'slug' => 'late-checkout-notes',
        'title' => 'Late Checkout Notes',
        'synopsis' => 'Simple Premium release with a direct layout.',
        'creator_name' => 'Nadia Vale',
        'category' => 'Solo',
        'access_level' => 'premium',
        'duration_minutes' => 31,
        'poster_tone' => 0,
        'poster_path' => null,
        'video_url' => null,
        'file_path' => null,
        'trailer_url' => null,
        'embed_url' => null,
        'mime_type' => null,
        'original_source_url' => null,
        'source_type' => 'upload',
        'storage_provider' => 'local',
        'is_featured' => 0,
        'moderation_status' => 'approved',
        'published_at' => '2026-03-09 20:30:00',
    ],
    [
        'slug' => 'consent-ledger-berlin',
        'title' => 'Consent Ledger / Berlin',
        'synopsis' => 'Premium archive item with creator records on file.',
        'creator_name' => 'Atelier 24',
        'category' => 'Couples',
        'access_level' => 'premium',
        'duration_minutes' => 47,
        'poster_tone' => 2,
        'poster_path' => null,
        'video_url' => null,
        'file_path' => null,
        'trailer_url' => null,
        'embed_url' => null,
        'mime_type' => null,
        'original_source_url' => null,
        'source_type' => 'upload',
        'storage_provider' => 'local',
        'is_featured' => 0,
        'moderation_status' => 'approved',
        'published_at' => '2026-03-04 17:05:00',
    ],
    [
        'slug' => 'membership-briefing-cut',
        'title' => 'Membership Briefing Cut',
        'synopsis' => 'Short free clip used as a simple onboarding sample.',
        'creator_name' => 'Platform Originals',
        'category' => 'Behind the Scenes',
        'access_level' => 'free',
        'duration_minutes' => 11,
        'poster_tone' => 3,
        'poster_path' => null,
        'video_url' => null,
        'file_path' => null,
        'trailer_url' => null,
        'embed_url' => null,
        'mime_type' => null,
        'original_source_url' => null,
        'source_type' => 'upload',
        'storage_provider' => 'local',
        'is_featured' => 0,
        'moderation_status' => 'approved',
        'published_at' => '2026-03-01 09:15:00',
    ],
];
