<?php

declare(strict_types=1);

$defaults = [
    'header' => [
        'nav' => [
            'home' => 'Home',
            'browse' => 'Browse',
            'premium' => 'Premium',
            'support' => 'Support',
            'admin' => 'Admin',
            'account' => 'My account',
            'sign_in' => 'Sign in',
            'join' => 'Join',
            'member_fallback' => 'Member',
            'log_out' => 'Log out',
        ],
        'bar' => [
            'home' => [
                'item_1' => 'Creator-ready video platform',
                'item_2' => 'Flexible access controls',
                'item_3' => 'Free and Premium access',
            ],
            'browse' => [
                'item_1' => 'Search and filters',
                'item_2' => 'Fast library browsing',
                'item_3' => 'Free and Premium catalog',
            ],
            'premium' => [
                'item_1' => 'Secure checkout',
                'item_2' => 'Recurring memberships',
                'item_3' => 'Free and Premium access',
            ],
            'support' => [
                'item_1' => 'Account and billing help',
                'item_2' => 'Legal contact',
                'item_3' => 'Platform guidance',
            ],
            'legal' => [
                'item_1' => 'Policies and support',
                'item_2' => 'Public information',
                'item_3' => 'Helpful links',
            ],
            'account' => [
                'item_1' => 'Signed in',
                'item_2' => 'Member area',
                'item_3' => 'Security and billing',
            ],
        ],
    ],
    'common' => [
        'watch_now' => 'Watch now',
        'open_support' => 'Open support',
        'browse_videos' => 'Browse videos',
        'see_premium' => 'See Premium',
        'view_plans' => 'View plans',
        'create_account' => 'Create account',
        'go_to_account' => 'Go to my account',
        'back_to_home' => 'Back to home',
        'back_to_sign_in' => 'Back to sign in',
        'back_to_browse' => 'Back to browse',
    ],
    'home' => [
        'title_suffix' => 'Video Platform',
        'hero_eyebrow' => 'VIDEO PLATFORM',
        'hero_title' => 'Launch a clean video experience.',
        'hero_description' => 'Show free and premium videos with a simpler browsing flow, cleaner labels, and a faster path to playback.',
        'hero_primary_cta' => 'Browse videos',
        'hero_secondary_cta' => 'See Premium',
        'stats_library_label' => 'Library',
        'stats_library_value_note' => 'published videos',
        'stats_creators_label' => 'Creators',
        'stats_creators_value_note' => 'active profiles',
        'stats_premium_label' => 'Premium',
        'stats_premium_value_note' => 'paid items',
        'fallback_notice_title' => 'Catalog preview',
        'fallback_notice_text' => 'A preview selection is showing right now. The full library will appear here when your site is fully connected.',
        'featured_eyebrow' => 'FEATURED',
        'featured_title' => 'Start with the featured picks',
        'featured_description' => 'Use the home page for quick discovery, then jump into the full browse view when you want filters.',
        'quick_eyebrow' => 'QUICK BROWSE',
        'quick_title' => 'Preview the latest uploads',
        'quick_description' => 'Keep browsing on the dedicated library page for search, filters, and sorting.',
        'next_eyebrow' => 'NEXT STEP',
        'next_title' => 'Open the full library',
        'next_description' => 'Search by title, creator, category, or access level on the dedicated browse page.',
        'next_primary_cta' => 'Open browse page',
        'next_secondary_cta' => 'Need help?',
        'membership_eyebrow' => 'MEMBERSHIP',
        'membership_title' => 'Choose how you want to watch',
        'membership_description' => 'Free videos stay open to everyone. Premium videos stay reserved for paying members.',
        'free_badge' => 'Free',
        'free_title' => 'Open access videos',
        'free_text' => 'Watch any video marked Free without payment. Create an account only when you want saved access, billing, or added security.',
        'free_cta' => 'Browse free videos',
        'premium_badge' => 'Premium',
        'premium_title' => 'One plan for every Premium title',
        'premium_text' => 'Use one membership to unlock all Premium videos, then manage billing from your account whenever you need.',
        'premium_primary_cta' => 'View plans',
        'premium_secondary_cta' => 'Payment help',
    ],
    'browse' => [
        'meta_title' => 'Browse',
        'meta_description' => 'Browse the full library with filters for title, creator, category, and access level.',
        'hero_eyebrow' => 'BROWSE',
        'hero_title' => 'Find videos faster.',
        'hero_description' => 'Search by title or creator, filter by category, and switch between Free and Premium in one place.',
        'hero_primary_cta' => 'Start browsing',
        'hero_secondary_cta' => 'See Premium',
        'stats_total_label' => 'Total videos',
        'stats_premium_label' => 'Premium videos',
        'stats_creators_label' => 'Creators',
        'featured_eyebrow' => 'FEATURED NOW',
        'featured_title' => 'Quick starts',
        'featured_description' => 'Start with one of the current highlights, then keep filtering below.',
        'library_eyebrow' => 'FULL LIBRARY',
        'library_title' => 'Search, filter, and sort',
        'library_description' => 'Keep the homepage lighter and use this page when you want the full browsing workflow.',
        'help_eyebrow' => 'HELP',
        'help_title' => 'Need account or billing help?',
        'help_description' => 'Open support for account access, Premium questions, legal contact, and platform rules.',
        'help_primary_cta' => 'Open support',
        'help_secondary_signed_in' => 'Go to my account',
        'help_secondary_guest' => 'Create account',
        'catalog' => [
            'search_label' => 'Search by title or creator',
            'search_placeholder' => 'Search titles or creators',
            'results_label' => 'Results',
            'premium_label' => 'Premium videos',
            'total_label' => 'Total library',
            'category_label' => 'Category',
            'access_label' => 'Access',
            'sort_label' => 'Sort',
            'access_all' => 'All',
            'access_free' => 'Free',
            'access_premium' => 'Premium',
            'sort_recent' => 'Newest',
            'sort_duration' => 'Longest',
            'sort_title' => 'A-Z',
            'results_one' => 'video found',
            'results_many' => 'videos found',
            'summary_fallback' => 'Preview catalog is active.',
            'summary_live' => 'Browse the latest videos below.',
            'empty_eyebrow' => 'NO RESULTS',
            'empty_title' => 'No videos match your filters.',
            'empty_text' => 'Try another word or change one of the filters.',
        ],
    ],
    'support' => [
        'meta_title' => 'Support',
        'meta_description' => 'Get help with account access, Premium billing, legal notices, and platform rules.',
        'hero_eyebrow' => 'SUPPORT',
        'hero_title' => 'Help users find the right next step.',
        'hero_description' => 'Use this page for account access, Premium billing questions, legal notices, and general site guidance.',
        'hero_primary_cta' => 'Email support',
        'hero_secondary_cta' => 'Read platform rules',
        'email_title' => 'Support email',
        'email_empty' => 'Add a support email from the admin panel to show contact details here.',
        'best_for_title' => 'Best for',
        'best_for_text' => 'Account access, Premium payments, policy questions, and takedown or compliance contact.',
        'topics_eyebrow' => 'HELP TOPICS',
        'topics_title' => 'Choose the right path',
        'topics_description' => 'Keep support organized by the job the visitor needs to complete.',
        'accounts_badge' => 'Accounts',
        'accounts_title' => 'Sign in and account access',
        'accounts_text' => 'Use these pages when someone needs to sign in, register, reset a password, or manage account security.',
        'billing_badge' => 'Premium',
        'billing_title' => 'Plans and billing',
        'billing_text' => 'Show visitors how Free and Premium access works and where they can manage an active subscription.',
        'billing_link_signed_in' => 'Membership status',
        'policies_badge' => 'Policies',
        'policies_title' => 'Rules and legal information',
        'policies_text' => 'Use these pages for platform rules, terms, privacy, and cookie information.',
        'discovery_eyebrow' => 'DISCOVERY',
        'discovery_title' => 'Still browsing?',
        'discovery_text' => 'Head back to the public catalog to browse Free and Premium titles with filters and sorting.',
        'discovery_primary_cta' => 'Browse videos',
        'discovery_secondary_cta' => 'See Premium',
    ],
    'premium' => [
        'bar_price_title' => 'Price',
        'bar_split_title' => 'Catalog split',
        'bar_account_title' => 'Your account',
        'hero_eyebrow' => 'PREMIUM ACCESS',
        'hero_primary_cta' => 'Upgrade now',
        'hero_manage_cta' => 'Manage plan',
        'hero_guest_cta' => 'Create free account',
        'hero_secondary_cta' => 'Browse videos',
        'disabled_title' => 'Premium access is not available right now',
        'disabled_text_public' => 'Please check back soon.',
        'disabled_text_admin' => 'Finish the payment setup in the admin panel to open Premium memberships.',
        'disabled_link' => 'Open payment settings',
        'plans_eyebrow' => 'PLANS',
        'plans_title' => 'Free vs Premium',
        'plans_description' => 'Free videos stay open to everyone. Premium videos require a signed-in Premium member.',
        'free_badge' => 'Free',
        'free_title' => 'Free account',
        'free_text' => 'Watch every video marked as free with no payment required.',
        'free_item_1' => 'No login required for free videos',
        'free_item_2' => 'Create an account to manage security and upgrades',
        'free_item_3' => 'Upgrade anytime from your account',
        'free_link_signed_in' => 'Open account',
        'free_link_guest' => 'Create account',
        'premium_item_1' => 'Required for every video marked Premium',
        'premium_item_2' => 'Manage payment details and cancel anytime',
        'premium_item_3' => 'Your access updates automatically after payment',
        'premium_checkout_cta' => 'Start secure checkout',
        'premium_manage_cta' => 'Manage plan',
        'premium_guest_cta' => 'Sign in to upgrade',
        'premium_unavailable_note' => 'Premium access is temporarily unavailable.',
        'rules_eyebrow' => 'ACCESS RULES',
        'rules_title' => 'What Premium changes',
        'rules_description' => 'Keep the difference simple so visitors understand what each label means before checkout.',
        'rule_free_title' => 'Free',
        'rule_free_text' => 'Videos marked as free can be watched by any visitor, even without a login.',
        'rule_premium_title' => 'Premium',
        'rule_premium_text' => 'Videos marked as Premium only play for signed-in members with an active Premium plan.',
        'rule_checkout_title' => 'Checkout',
        'rule_checkout_text' => 'The upgrade flow opens a secure payment page and returns here when payment is complete.',
        'rule_manage_title' => 'Manage plan',
        'rule_manage_text' => 'Existing subscribers can update payment details or cancel their plan from their account.',
        'support_eyebrow' => 'SUPPORT',
        'support_title' => 'Need help before upgrading?',
        'support_text' => 'Use the support page for account access, billing help, and legal contact information.',
        'support_cta' => 'Open support',
    ],
    'watch' => [
        'meta_missing_title' => 'Video not found',
        'missing_eyebrow' => '404',
        'missing_title' => 'Video not found',
        'missing_text' => 'This video is unavailable or has been removed.',
        'missing_cta' => 'Back to browse',
        'stage_back_cta' => 'Back to browse',
        'stage_premium_cta' => 'See Premium',
        'premium_badge' => 'Premium only',
        'premium_text' => 'Sign in with a Premium account to watch this video.',
        'premium_user_cta' => 'Upgrade to Premium',
        'premium_guest_cta' => 'Sign in',
        'premium_secondary_cta' => 'View plans',
        'preview_badge' => 'Preview unavailable',
        'preview_text' => 'Playback is not available for this video yet.',
        'meta_creator' => 'Creator',
        'meta_length' => 'Length',
        'meta_published' => 'Published',
        'facts_access' => 'Access',
        'notice_title' => '18+ notice',
        'notice_text' => 'This page contains adult material and is only for viewers 18 or older.',
        'plan_title' => 'Plan required',
        'plan_text_allowed' => 'This account currently has Premium access.',
        'plan_text_blocked' => 'This title is Premium and requires an active Premium account.',
        'plan_link' => 'Open Premium plans',
        'help_title' => 'Need help?',
        'help_text' => 'Use the support page for account, billing, or legal contact details.',
        'help_link' => 'Open support',
        'original_url_title' => 'Original URL',
        'related_eyebrow' => 'RELATED',
        'related_title' => 'More in this category',
    ],
    'account' => [
        'title' => 'Account',
        'bar' => [
            'item_1' => 'Signed in',
            'item_2' => 'Member area',
            'item_3' => 'Security and billing',
        ],
        'eyebrow' => 'ACCOUNT',
        'intro' => 'Keep membership, security, and account help grouped in one place.',
        'summary_plan' => 'Plan',
        'summary_status' => 'Status',
        'summary_security' => 'Security',
        'summary_security_on' => '2FA on',
        'summary_security_off' => '2FA off',
        'subscription_title' => 'Subscription',
        'subscription_plan' => 'Plan:',
        'subscription_status' => 'Membership status:',
        'subscription_until' => 'Access until:',
        'subscription_manage_cta' => 'Manage plan',
        'subscription_upgrade_cta' => 'Upgrade to',
        'subscription_unavailable' => 'Premium access is not available right now.',
        'subscription_link' => 'See plans',
        'profile_title' => 'Profile',
        'profile_email' => 'Email:',
        'profile_type' => 'Account type:',
        'profile_status' => 'Account status:',
        'profile_link' => 'Go to browse',
        'security_title' => 'Security',
        'security_status' => '2FA:',
        'security_enabled' => 'Enabled',
        'security_disabled' => 'Disabled',
        'security_text' => 'Use an authenticator app for extra sign-in protection. Backup codes help you get back in if you lose your device.',
        'security_code_label' => 'Authenticator or backup code',
        'security_disable_cta' => 'Disable 2FA',
        'security_key_title' => 'Authenticator key',
        'security_setup_link_title' => 'Setup link',
        'security_enable_code_label' => '6-digit code',
        'security_enable_cta' => 'Enable 2FA',
        'security_start_cta' => 'Start 2FA setup',
        'backup_codes_title' => 'Backup codes',
        'backup_codes_text' => 'Save these codes now. They are shown only once.',
        'password_reset_title' => 'Password reset',
        'password_reset_text' => 'If you lose access, use the reset page to request a new password link.',
        'password_reset_link' => 'Open password reset',
        'admin_title' => 'Admin',
        'admin_storage' => 'Current storage:',
        'admin_text' => 'Open the control panel to manage videos, members, payments, and site settings.',
        'primary_cta' => 'Browse videos',
        'secondary_cta' => 'Get help',
        'admin_cta' => 'Open admin',
        'logout_cta' => 'Sign out',
    ],
    'auth' => [
        'login' => [
            'title' => 'Sign in',
            'eyebrow' => 'ACCESS',
            'heading' => 'Sign in',
            'text' => 'Sign in to watch premium videos and manage your account.',
            'email' => 'Email',
            'password' => 'Password',
            'submit' => 'Sign in',
            'forgot' => 'Forgot your password?',
            'register_prompt' => 'No account yet?',
            'register_link' => 'Create one',
        ],
        'register' => [
            'title' => 'Create account',
            'eyebrow' => 'JOIN',
            'heading' => 'Create your account',
            'text' => 'Create a free account to save your access and upgrade anytime.',
            'display_name' => 'Display name',
            'email' => 'Email',
            'birth_date' => 'Birth date',
            'password' => 'Password',
            'password_confirmation' => 'Confirm password',
            'terms' => 'I confirm that I meet the platform age requirement and I accept the site policy.',
            'submit' => 'Create account',
        ],
        'forgot' => [
            'title' => 'Reset password',
            'eyebrow' => 'PASSWORD RESET',
            'heading' => 'Reset access',
            'text' => 'Enter your email and we will help you reset your password.',
            'email' => 'Email',
            'submit' => 'Send reset link',
            'preview_enabled' => 'Reset link preview is enabled for this site right now.',
            'preview_disabled' => 'If the email matches an account, the next step will be sent to you.',
            'preview_title' => 'Reset link',
            'preview_link' => 'Open reset page',
        ],
        'reset' => [
            'title' => 'New password',
            'eyebrow' => 'RESET',
            'heading' => 'Choose a new password',
            'text' => 'Use a strong password with at least 8 characters.',
            'success_cta' => 'Go to sign in',
            'invalid_title' => 'Reset link unavailable',
            'invalid_text' => 'This reset link is not valid anymore. Request a new one and try again.',
            'password' => 'New password',
            'password_confirmation' => 'Confirm new password',
            'submit' => 'Save new password',
        ],
        'mfa' => [
            'title' => '2FA challenge',
            'eyebrow' => '2FA',
            'heading' => 'Enter your code',
            'text' => 'Use the 6-digit code from your authenticator app or one of your backup codes.',
            'code_label' => 'Authenticator or backup code',
            'submit' => 'Verify code',
            'note' => 'Backup codes can be entered with or without hyphens.',
        ],
    ],
    'age_gate' => [
        'eyebrow' => '18+ ONLY',
        'title' => 'Before you enter',
        'text' => 'This site contains age-restricted content and is only for people who are 18 or older.',
        'item_1' => 'By entering, you confirm that you are 18 or older.',
        'item_2' => 'Restricted content stays clearly marked across the site.',
        'item_3' => 'You can leave this page at any time.',
        'confirm' => 'I am 18+',
        'leave' => 'Leave',
        'saving' => 'Saving your confirmation...',
        'error' => 'Something went wrong. Please try again.',
        'save_error' => 'We could not save your confirmation.',
    ],
    'messages' => [
        'common' => [
            'security_token_expired' => 'Security token expired. Try again.',
            'sign_in_required' => 'Sign in to continue.',
        ],
        'auth' => [
            'login_unavailable' => 'Sign in is temporarily unavailable. Please try again later.',
            'invalid_credentials' => 'Invalid email or password.',
            'account_suspended' => 'This account is suspended.',
            'mfa_required' => 'Enter your 2FA code to continue.',
            'login_success' => 'Signed in successfully.',
            'required_fields' => 'Fill in all required fields.',
            'invalid_email' => 'Enter a valid email address.',
            'password_too_short' => 'Password must be at least 8 characters long.',
            'password_confirmation_mismatch' => 'Password confirmation does not match.',
            'age_confirmation_required' => 'You must confirm that you meet the site age requirement and accept the site policy.',
            'invalid_birth_date' => 'Invalid birth date.',
            'registration_age_restricted' => 'Registration is available only to users who meet the site age requirement.',
            'email_exists' => 'An account with this email already exists.',
            'register_success_admin' => 'Account created. This first account has admin access.',
            'register_success_member' => 'Account created successfully.',
            'reset_requested' => 'If the account exists, a reset link has been generated.',
            'reset_preview_ready' => 'Reset link is ready.',
            'reset_invalid_token' => 'Invalid reset token.',
            'reset_expired' => 'Reset link expired or already used.',
            'reset_success' => 'Password updated. You can sign in now.',
            'mfa_session_expired' => 'Your MFA session expired. Sign in again.',
            'mfa_invalid_code' => 'Invalid 2FA code.',
            'mfa_backup_success' => 'Backup code accepted. You are now signed in.',
            'mfa_success' => '2FA verified. You are now signed in.',
            'account_not_found' => 'Account not found.',
            'mfa_already_enabled' => '2FA is already enabled.',
            'mfa_setup_started' => '2FA setup started. Add the key to your authenticator app and confirm with a code.',
            'mfa_start_first' => 'Start the 2FA setup first.',
            'mfa_invalid_authenticator_code' => 'Invalid authenticator code.',
            'mfa_enabled_success' => '2FA enabled. Save the backup codes now.',
            'mfa_not_enabled' => '2FA is not enabled for this account.',
            'mfa_disabled_success' => '2FA disabled.',
            'mfa_page_sign_in_again' => 'Sign in again to continue.',
            'throttle_one' => 'Too many attempts. Try again in about 1 minute.',
            'throttle_many' => 'Too many attempts. Try again in about {minutes} minutes.',
        ],
        'billing' => [
            'premium_unavailable' => 'Premium access is not available right now.',
            'already_premium' => 'This account already has Premium access.',
            'checkout_start_failed' => 'We could not start checkout right now.',
            'portal_unavailable' => 'This account does not have plan management available yet.',
            'portal_open_failed' => 'We could not open plan management right now.',
            'checkout_confirm_failed' => 'We could not confirm your payment.',
            'checkout_account_mismatch' => 'This payment confirmation does not match your account.',
            'checkout_success' => 'Your Premium access is now active.',
            'checkout_success_guest' => 'Your payment is confirmed. Sign in to refresh your account.',
            'checkout_canceled' => 'Checkout was canceled before payment was completed.',
        ],
    ],
];

$setNested = static function (array $target, string $path, mixed $value) use (&$setNested): array {
    $segments = explode('.', $path);
    $segment = array_shift($segments);

    if ($segment === null || $segment === '') {
        return $target;
    }

    if ($segments === []) {
        $target[$segment] = $value;
        return $target;
    }

    $child = isset($target[$segment]) && is_array($target[$segment]) ? $target[$segment] : [];
    $target[$segment] = $setNested($child, implode('.', $segments), $value);

    return $target;
};

$rawOverrides = trim((string) env_value('VIDEW_COPY_OVERRIDES_B64', ''));

if ($rawOverrides !== '') {
    $decoded = base64_decode($rawOverrides, true);
    $parsed = json_decode(is_string($decoded) ? $decoded : '', true);

    if (is_array($parsed)) {
        foreach ($parsed as $path => $value) {
            if (is_string($path) && is_string($value)) {
                $defaults = $setNested($defaults, $path, $value);
            }
        }
    }
}

return $defaults;
